### ISSUE TITLE
Strange visual rendering

### ISSUE THREAD

**Issue by jasonkuhrt** [fisadev/vim-ctrlp-cmdpalette#6]
This is a really helpful plugin in a space that is almost completely underserved in vim. The command line is one place where vim is basically simply not good regardless of wildmode etc.

Anyways, this is the best plugin I've found so far so thanks. Its still iffy but you've done more work than I'm willing to so can't complain!

I noticed something funky with the rendering, any ideas?

Before execution:
![before](https://cloud.githubusercontent.com/assets/284476/6548080/c63033ac-c5c3-11e4-82dc-dee11cd98221.png)

After:
![image](https://cloud.githubusercontent.com/assets/284476/6548074/ab9c0cb4-c5c3-11e4-8521-e2afb9bbfdc7.png)

**Comment by fisadev** [comment]
Strange!
Which version of vim are you using? And do you have the last version of CtrlP? Just updated to test it with the current version, and it works fine here, so I can't debug the bug on my vim.
Can you post a screenshot of CtrlP when using any of the default finders? (like the file finder)

**Comment by jasonkuhrt** [comment]
Everything is newly installed. I am guessing there is just a conflict with plugins. Typical `vim` life, sigh.

**Comment by fisadev** [comment]
But does this happen with the default finders? And are you using airline, powerline, or something like that?

**Comment by jasonkuhrt** [comment]
> But does this happen with the default finders?

I don't understand the question so probably yes.

> And are you using airline, powerline, or something like that?

Nope.

**Comment by fisadev** [comment]
> > But does this happen with the default finders?

> I don't understand the question so probably yes.

This repo is an extension to CtrlP. CtrlP provides finders for files, tags, etc. This repo is an extension to provide a finder for commands, which you are using in the screenshot. But I only implemented the "source" of the commands list, and a definition for CtrlP to expose that list as a new finder. All the displaying and filtering is done by the original CtrlP plugin, which I don't develop.

What I was asking for was: do you see the same problem when using the finders that CtrlP has by default? The fuzzy file finder, for example.

**Comment by jasonkuhrt** [comment]
Yep:

![screen shot 2015-03-10 at 4 19 29 pm](https://cloud.githubusercontent.com/assets/284476/6584387/460d5dce-c741-11e4-8ff9-7f13eccade00.png)

**Comment by fisadev** [comment]
Ok! then it's a CtrlP problem. I recommend reporting it in their repo: https://github.com/kien/ctrlp.vim

**Comment by jasonkuhrt** [comment]
Will do.
