### ISSUE TITLE
No syntastic commands in cmdpalette

### ISSUE THREAD

**Issue by yevhen-m** [fisadev/vim-ctrlp-cmdpalette#9]
Why I don't see all syntastic commands in cmdpalette window?
![image](https://cloud.githubusercontent.com/assets/10185058/15191456/7095426e-17bd-11e6-83e4-416f69380563.png)

**Comment by fisadev** [comment]
Good question. I'll have to debug a little to see what's happening

**Comment by fisadev** [comment]
Have you tried typing more than just "sy" for a better match? In my vim, if I type something like "syntas" I can see all the other syntastic commands:

![commands](https://cloud.githubusercontent.com/assets/251215/15222940/4f46c804-1848-11e6-90c7-81a9e606b7eb.png)

**Comment by yevhen-m** [comment]
No, I still don't see them.
![image](https://cloud.githubusercontent.com/assets/10185058/15224370/9e7060fa-1881-11e6-976d-ee975547fbe0.png)

**Comment by yevhen-m** [comment]
Hey, I've figured out the problem. It was my configuration for this plugin.
Sorry for bothering your for nought.

**Comment by fisadev** [comment]
No problem! Glad you found a fix :)
